### ISSUE TITLE
Can it directly show the routes in google map or apple map between 2 locations?

### ISSUE THREAD

**Issue by shan1iu** [brh55/react-native-open-maps#13]

**Comment by brh55** [comment]
@shan1iu currently not supported, but it's possible to add this to the library!

**Comment by brh55** [comment]
@shan1iu I can add, or you are more than welcome to do it!

**Comment by shan1iu** [comment]
thanks for your reply. this is a very awesome tool.

**Comment by brh55** [comment]
Would you be open to trying out the latest PR #14 , this includes the directions capabilities. I haven't been able to QA it, only coded it per the both specs, so no guarantees 🗡  @shan1iu 

Couple ways to test this:
1. Clone repo into your node modules, git checkout the `directions` branch

or 

1. Copy index.js from the `directions` branch as copy it into your own internal component

**Comment by shan1iu** [comment]
Cheers mate
