### ISSUE TITLE
Cannot drop a marker

### ISSUE THREAD

**Issue by NichAga** [brh55/react-native-open-maps#15]
Hi,
If I open the map with longitude and latitude, I'm not able to get the marker on the corrispondent maps app on Android & iOS, it opens to the coordinates but it doesn't drop the marker.
I also tried to set "latitude,longitude" in the query parameter but it's still not present.

Thanks,
Nicholas.

**Comment by brh55** [comment]
@NichAga Are you using v0.3.1?

I'm not having that issue with Apple maps (using latitude + longitude + query) or Google maps using (Query) doesn't support markers unless you.

![image](https://user-images.githubusercontent.com/6020066/44484888-d4329e80-a603-11e8-9415-16696a60e3e2.png)
![image](https://user-images.githubusercontent.com/6020066/44484895-da287f80-a603-11e8-920e-2540a0c30624.png)

**Comment by NichAga** [comment]
@brh55 With only query, without longitude and latitude, on Android works.

**Comment by Shahrukh0396** [comment]
onPress={openMap(Platform.OS === 'ios' ?
        {
          latitude: 37.865101,
          longitude: -119.538330,
          query: 'Yosemite Trails',
          zoom: 16,
          provider: Platform.OS === 'android' ? 'google' : 'apple'
        } :
        {
          query: '37.865101,-119.538330',
          zoom: 16,
          provider: 'google'
        }
      )}
