### ISSUE TITLE
Location name 'Pin' is posible to rename?

### ISSUE THREAD

**Issue by felipevila** [brh55/react-native-open-maps#17]
When I open the location based on map coordinates (latitude and longitude) it opens with a default title of 'Pin'. Is it possible to change it?

**Comment by brh55** [comment]
@felipevila  
Update to the latest version, and use a combination of different parameters to achieve desired result. Be warned this feature only works on Apple, due to differences in the nature of both map platforms.

> Apple Maps: If latitude and longitude is provided, this will place a marker with the query as a label. If no latitude or longitude is provided, it will center map to closest query match.
