### ISSUE TITLE
Apple Map travel type

### ISSUE THREAD

**Issue by tindn** [brh55/react-native-open-maps#18]
The apple map query param for travel type is incorrect.
Currently, the param name is [`dirflag` ](https://github.com/brh55/react-native-open-maps/blob/master/index.js#L45). From [documentation](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html), it should be `dirflg`.

I have verified that the current name isn't working and fixing the name will open apple maps with the right type.

This is a simple fix, I'm more than happy to submit a PR if you'd like.

**Comment by tindn** [comment]
Thanks for making the fix. Sorry I missed this notification.

**Comment by brh55** [comment]
@tindn No worries, but thank you for bringing it to my attention!
