### ISSUE TITLE
Link to Docs for start/end Geolocation Strings

### ISSUE THREAD

**Issue by stdavis** [brh55/react-native-open-maps#22]
Thanks for the super-useful module!

I'm looking for more specifics on what I can pass to `start` & `end`. Do you have links to the google and apple APIs for this information? If so, it may be helpful to add these links to your documentation. If you agree with this, I'd be happy to submit a PR to do so.

**Comment by brh55** [comment]
@stdavis 
Absolutely,
- [Apple URL Scheme](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html#//apple_ref/doc/uid/TP40007899-CH5-SW1)
- [Google Map URL](https://developers.google.com/maps/documentation/urls/guide)

Feel free to submit any PR to improve on the documentation, any way to improve on the usability is always appreciated!
