### ISSUE TITLE
Maps are open in preview mode

### ISSUE THREAD

**Issue by nwaughachukwuma** [brh55/react-native-open-maps#26]
@brh55 the maps are currently being open in preview modes, and as am working on a ride sharing service, I need a way to ensure that maps are opened in navigation mode. Please how do I go about this? Thanks

**Comment by brh55** [comment]
@nwaughachukwuma Won't be able to perform that navigation intent with this package as it uses cross-platform URLs, which have the limitations to support a broader set of platforms. 

There is a similar package, [react-native-open-map](https://www.npmjs.com/package/react-native-open-map), that uses a deep link which can perform what you are doing, you'll need some prior configuration in the Info.plist.
