### ISSUE TITLE
Opening Maps in navigation mode

### ISSUE THREAD

**Issue by nwaughachukwuma** [brh55/react-native-open-maps#27]
Hi @brh55 is there any reason why the maps are not being opened in navigation mode? I.e. for Google maps `dir_action=navigate`. Is it a design thing? Or does the library not aim to achieve this? Please let me know, as am able to do a PR to add that behaviour. Thanks

**Comment by nwaughachukwuma** [comment]
@brh55, based on your answer to #26 am closing this

**Comment by brh55** [comment]
@nwaughachukwuma Actually I wouldn't be oppose to a PR, though you may need to ensure the apple maps can perform a similar action to minimize drift.

**Comment by nwaughachukwuma** [comment]
@brh55 both maps open in navigation mode when the start point is omitted (not provided). The maps (apple and google) use the user's current location as indicated by device GPS as the start point and displays in `navigation mode`. Though for android, there's a need to add dir_action=navigate as part of the URL params

**Comment by nwaughachukwuma** [comment]
I'd send in a PR and have you see what I have in mind

**Comment by brh55** [comment]
Makes perfect sense, if it's supported on both ends then it's perfectly in scope. Feel free to send that PR over when you are ready.

**Comment by nwaughachukwuma** [comment]
PR sent and merged. Thanks @brh55
