### ISSUE TITLE
Open Google and Apple maps with waypoints

### ISSUE THREAD

**Issue by alexeyvax** [brh55/react-native-open-maps#30]
Hey @brh55,

I would like to ask you, does this lib support opening Google and Apple maps with waypoints?

Thanks.

**Comment by brh55** [comment]
Does not support waypoint, I would have to see if it's available in the URL scheme.

**Comment by alexeyvax** [comment]
> Does not support waypoint
It's too pity

> I would have to see if it's available in the URL scheme.
Would appreciate if you take a look at it!

**Comment by smm76** [comment]
@alexeyvax you can achieve this by simply using RNs Linking module. 
You could use it like this `Linking.openURL('https://maps.apple.com/?daddr='+URI_ENCODED_ADDRESS)`
For Google Maps use `Linking.openURL('https://maps.google.com/?daddr='+URI_ENCODED_ADDRESS)`
This will open Maps App with directions to your given address.

**Comment by alexeyvax** [comment]
@smm76  Yes, you are right, but I'm looking for possibility to open apple map with additional points between start and and points. As far as I know google maps have this functionality (https://developers.google.com/maps/documentation/directions/intro#optional-parameters called waypoints). Just need to use query param `&waypoints=`, but apple doesn't.

**Comment by brh55** [comment]
Merged #75
