### ISSUE TITLE
Can't find variable: defaultProvider

### ISSUE THREAD

**Issue by Devon66h** [brh55/react-native-open-maps#36]
Hey there,

I have implemented the example shown in the documentation but get an error: 

ReferenceError: Can't find variable: defaultProvider

Thanks for your help.

**Comment by prasad456** [comment]
@Devon66h have you fixed the issue

**Comment by lhammond** [comment]
@Devon66h @prasad456 I'm having the same on android.
any ideas?

**Comment by ArnoviMoinuddin** [comment]
Was anyone able to resolve this @Devon66h @ihammond @prasad456
