### ISSUE TITLE
Add a pin on map from lat and long

### ISSUE THREAD

**Issue by SandeshVakale** [brh55/react-native-open-maps#4]
This is the question and not a issue. I am new in react native and do make mistakes because I am fool, idiot, etc ...

Is it possible to add pin when we open native maps through openMap API? 
Can you give example if it is possible?

Thanks in advance for your respond.

**Comment by brh55** [comment]
@SandeshVakale 
First off don't ever call yourself a fool/idiot, :). 

Anyways for the `react-native-open-maps` v0.1.2, and you'll see a pin for apple maps, no changes needed :)

**Comment by josermorales** [comment]
its not showing for me :/
