### ISSUE TITLE
Way to pass Location Name

### ISSUE THREAD

**Issue by bamne123** [brh55/react-native-open-maps#6]
After opening the location in Google maps, it points to proper location, but name says `Unnamed Location`. Can you implement way to pass the name to Google maps?

**Comment by brh55** [comment]
@bamne123 That sounds like a great enhancement, unfortunately I'm busy for the next few weeks for work-related deadlines. It's quite easy to implement if someone wants to tackle this 👍!

**Comment by brycelund** [comment]
Added in #7

**Comment by brh55** [comment]
Now available in v0.1.4 thanks @brycelund
