### ISSUE TITLE
Pin point location not showing on IOS map

### ISSUE THREAD

**Issue by Judono** [brh55/react-native-open-maps#64]
Hello, I just tried to use the code but for some reason when I open on the IOS map it does not show the pin point location but it does show the area of the latitude and longitude, please help

(this is the code bellow)

<TouchableOpacity 
    style={styles.actionButton}
    onPress={() => {openMap({ latitude:-7.713009199999998, longitude:109.9184728 })}}>
        <MaterialCommunityIcons name="map-marker-radius" size={40} color="white" />
</TouchableOpacity>

**Comment by Judono** [comment]
[fixed] so I found that the solution was I need to add the query and it would show on maps

fixed code:

<TouchableOpacity
style={styles.actionButton}
onPress={() => {openMap({ latitude:-7.713009199999998, longitude:109.9184728, query:'some query' })}}>

**Comment by brh55** [comment]
Do you want to document this on the readme as perhaps an example? I would appreciate it!
