### ISSUE TITLE
Open a Route

### ISSUE THREAD

**Issue by ShubhamPatilsd** [brh55/react-native-open-maps#74]
hey,

so in my app im looking to open google maps or apple maps with multiple stops. currently with this library, i can only open one destination in the directions view. is it possible to add more than one? 

right now im thinking of creating a link that has multiple options and using deep links with `Linking` to open them

**Comment by brh55** [comment]
Hi @ShubhamPatilsd ,

The library doesn't support that. From the docs, Google Map does provide this functionality through `waypoints` in the url, but Apple maps doesn't. If you wanted to support this within your app for Google Maps, you could use the `createMapLink` function and append your waypoints to the Google Map url.

**Comment by brh55** [comment]
Looks like Apple does support multiple addresses
Based on this old issue: #30

**Comment by brh55** [comment]
Supported now @ShubhamPatilsd , 🍻 cheers!
